# Generated by Django 4.2.7 on 2026-08-06 13:14

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_secret_hash', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=255)),
                ('redirect_uris', models.TextField(help_text='Newline-separated list of allowed redirect URIs.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oauth_client',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True)),
                ('redirect_uri', models.TextField()),
                ('code_challenge', models.CharField(max_length=256)),
                ('code_challenge_method', models.CharField(default='S256', max_length=10)),
                ('expires_at', models.DateTimeField(default=authentication.models._default_expiry)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='authentication.oauthclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_authorization_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_authorization_code',
            },
        ),
    ]
