apiVersion: v1
kind: Secret
metadata:
  name: {{ include "classic-models-api.fullname" . }}
  labels:
    {{- include "classic-models-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  django-secret-key: {{ .Values.app.secretKey | quote }}
  mysql-password: {{ .Values.mysql.auth.password | quote }}
  {{- if .Values.app.apiKey }}
  api-key: {{ .Values.app.apiKey | quote }}
  {{- end }}

# Made with Bob
