{{- $skipSecretKey  := .Values.externalSecrets.djangoSecretKey.name }}
{{- $skipApiKey     := .Values.externalSecrets.apiKey.name }}
{{- $skipMysqlPass  := .Values.externalSecrets.mysqlPassword.name }}
{{- $hasOwned := or (not $skipSecretKey) (not $skipApiKey) (not $skipMysqlPass) }}
{{- if $hasOwned }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "classic-models-api.fullname" . }}
  labels:
    {{- include "classic-models-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not $skipSecretKey }}
  django-secret-key: {{ .Values.app.secretKey | quote }}
  {{- end }}
  {{- if not $skipMysqlPass }}
  {{- if .Values.mysql.enabled }}
  mysql-password: {{ .Values.mysql.auth.password | quote }}
  {{- else }}
  mysql-password: {{ .Values.externalDB.password | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.app.apiKey (not $skipApiKey) }}
  api-key: {{ .Values.app.apiKey | quote }}
  {{- end }}
{{- end }}

# Made with Bob
